<?php

/**
 * @file
 *  This ficticous module "Sugoi" is an example of how to implement Themepacket
 *  into your own modules. If something is worth mentioning it will be
 *  documented in the comments.
 */

/**
 * @todo form builder with theme function implementation
 * @todo form builder with tpl.php implementation
 * @todo form_alter with custom #theme
 * @todo block with tpl.php implementation
 * @todo block with theme function implementation
 */
/******************************************************************************
 * Drupal Hooks
 *****************************************************************************/

/**
 * Implementation of hook_menu().
 */
function sugoi_menu() {
  $items['sugoi/contents'] = array(
    'title' => 'Sugoi Contents',
    'description' => 'Table of contents for all menu items in this module.',
    'page callback' => 'theme',
    // Here we are using a theme function that themepacket had discovered in
    // the theme/contents directory. Notice that the theme hook is prefix with
    // the module name. Also, as an important FYI, the name "contents" was
    // derived from the filename contents.tpl.php, NOT the directory name. Once
    // in the "theme" directory, you have the liberty to organize your folders
    // any way you like, so structures like theme/page/main/contents.tpl.php
    // will still register "sugoi_contents" as a theme hook.
    'page arguments' => array('sugoi_contents'),
    'access callback' => TRUE,
  );
  
  $items['sugoi/sushi'] = array(
    'title' => 'Sugoi Page (as a theme function)',
    'description' => 'Example of a page callback that just returns theme().',
    'page callback' => 'sugoi_page_theme_function',
    'page arguments' => array(),
    'access callback' => TRUE,
  );
  
  $items['sugoi/wasabi'] = array(
    'title' => 'Sugoi Page (as a template)',
    'description' => 'Example of a page callback that just returns theme().',
    'page callback' => 'sugoi_page_template',
    'page arguments' => array(),
    'access callback' => TRUE,
  );
  
  $items['sugoi/gyoza'] = array(
    'title' => 'Sugoi Page (as a template with a preprocessor)',
    'description' => 'Example of a page callback that just returns theme().',
    'page callback' => 'sugoi_page_template_with_preprocessor',
    'page arguments' => array(),
    'access callback' => TRUE,
  );
  
  return $items;
}


/**
 * Implementation of hook_theme().
 */
function sugoi_theme($existing, $type, $theme, $path) {
  // Since this module depends on themepacket, we can simply return
  // themepacket_discover(), as opposed to the methods used in the "Kawaii"
  // theme, which has to first check if the module is available before calling
  // themepacket_discover().
  // 
  // If your module needs to manually register theme hooks, then it may do so
  // like this:
  // 
  // @code
  // 
  //  function mymodule_theme($existing, $type, $theme, $path) {
  //    $hooks['mymodule_samurai] = array(
  //      'arguments' => array('sword' => 'Hattori Hanzō', 'prefecture' => 'Okinawa'),
  //      'pattern' => 'mymodule_samurai__',
  //      'file' => 'mymodule.theme.inc',
  //    );
  //    return $hooks += themepacket_discover($existing, $type, $theme, $path);
  //  }
  // 
  // @endcode
  // 
  // Note that is is good practice to prefix your theme hooks with your module
  // name, as to avoid any namespace collisions with other modules' theme
  // hooks. Themepacket will always do this on your behalf.
  return themepacket_discover($existing, $type, $theme, $path);
}


/**
 * Page callback
 */
function sugoi_page_theme_function() {
  return theme('sugoi_sushi');
}

function sugoi_page_template() {
  return theme('sugoi_wasabi');
}

function sugoi_page_template_with_preprocessor() {
  return theme('sugoi_gyoza');
}